// Build a Chrome Web Store-ready zip containing only the files
// required at runtime. Sources, tests, and dev assets are excluded.

import { execSync } from 'node:child_process';
import { mkdirSync, rmSync, readFileSync, existsSync, cpSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();
const STAGE = join(ROOT, 'dist-package', 'staging');
const OUT_DIR = join(ROOT, 'dist-package');

const manifest = JSON.parse(readFileSync(join(ROOT, 'manifest.json'), 'utf8'));
const ZIP_NAME = `slate-v${manifest.version}.zip`;
const ZIP_PATH = join(OUT_DIR, ZIP_NAME);

// Files / dirs that go into the zip.
// Source TypeScript and tests are excluded; only built JS + html/css ship.
const INCLUDE = [
  'manifest.json',
  'assets/icons',
  'assets/lucide-icons.json',  // generated by build, NOT lucide-icons.full.json
  'dist/service-worker.js',
  'src/popup/popup.html',
  'src/popup/popup.css',
  'src/popup/popup.js',
  'src/manager/manager.html',
  'src/manager/manager.css',
  'src/manager/manager.js',
  'src/cli/cli.html',
  'src/cli/cli.js',
];

function ensureBuilt() {
  const required = [
    'dist/service-worker.js',
    'src/popup/popup.js',
    'src/manager/manager.js',
    'assets/lucide-icons.json',
  ];
  const missing = required.filter(p => !existsSync(join(ROOT, p)));
  if (missing.length) {
    throw new Error(`Missing build artefacts: ${missing.join(', ')}\nRun \`npm run build\` first.`);
  }
}

function stage() {
  rmSync(STAGE, { recursive: true, force: true });
  mkdirSync(STAGE, { recursive: true });

  for (const item of INCLUDE) {
    const src = join(ROOT, item);
    const dest = join(STAGE, item);
    if (!existsSync(src)) {
      throw new Error(`Required file missing: ${item}`);
    }
    mkdirSync(join(dest, '..'), { recursive: true });
    cpSync(src, dest, { recursive: true });
  }
}

function zip() {
  rmSync(ZIP_PATH, { force: true });
  // -r recursive, -X strip extra attrs, -q quiet
  execSync(`cd "${STAGE}" && zip -rqX "${ZIP_PATH}" .`, { stdio: 'inherit' });
}

function summarize() {
  const out = execSync(`unzip -l "${ZIP_PATH}"`).toString();
  console.log(out);
  const sizeKB = (execSync(`wc -c < "${ZIP_PATH}"`).toString().trim() / 1024).toFixed(1);
  console.log(`\n→ ${ZIP_NAME}  ${sizeKB} KB`);
}

ensureBuilt();
stage();
zip();
summarize();
rmSync(STAGE, { recursive: true, force: true });
